# Generated by Django 3.2.15 on 2023-03-31 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='app_name',
            field=models.CharField(default='financas', max_length=164),
            preserve_default=False,
        ),
    ]
