# Generated by Django 3.2.15 on 2023-07-17 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cevest_os', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cevest_ordemdeservico',
            name='logradouro',
        ),
        migrations.RemoveField(
            model_name='cevest_ordemdeservico',
            name='referencia',
        ),
        migrations.AlterField(
            model_name='cevest_ordemdeservico',
            name='bairro',
            field=models.CharField(max_length=150, verbose_name='local'),
        ),
        migrations.AlterField(
            model_name='cevest_ordemdeservico',
            name='motivo_reclamacao',
            field=models.TextField(verbose_name='Motivo da solicitação'),
        ),
        migrations.AlterField(
            model_name='cevest_ordemdeservico',
            name='nome_do_contribuinte',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nome do solicitante'),
        ),
        migrations.AlterField(
            model_name='cevest_ordemdeservico',
            name='telefone_do_contribuinte',
            field=models.CharField(blank=True, max_length=12, verbose_name='Telefone do solicitante'),
        ),
    ]
