# Generated by Django 2.1.7 on 2019-04-11 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Permissao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('pode_emitir_certificado', 'Pode emitir certificados'), ('acesso_admin', 'Acesso à area de admin')),
            },
        ),
    ]
