# Generated by Django 2.1.9 on 2019-07-06 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Administracao', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permissao',
            options={'permissions': (('pode_emitir_certificado', 'Pode emitir certificados'), ('acesso_admin', 'Acesso à area de admin'), ('eh_professor', 'Permissão para professores'))},
        ),
    ]
