# Generated by Django 3.2.9 on 2022-02-09 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administracao', '0002_auto_20190706_2030'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permissao',
            options={'permissions': (('pode_emitir_certificado', 'Pode emitir certificados'), ('acesso_admin', 'Acesso à area de admin'), ('eh_professor', 'Permissão para professores'), ('pode_fazer_alocacao', 'Permissão para fazer alocação'))},
        ),
        migrations.AlterField(
            model_name='permissao',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
