# Generated by Django 2.0.9 on 2018-12-27 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cevest', '0006_auto_20181226_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='quant_alunos',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='turma_prevista',
            name='quant_alunos',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
