# Generated by Django 2.0.9 on 2019-01-07 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cevest', '0011_auto_20190107_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='nis',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True),
        ),
    ]
