# Generated by Django 2.0.10 on 2019-01-22 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cevest', '0016_aluno_turma_prevista'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turma_Prevista_Turma_Definitiva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_inclusao', models.DateTimeField(auto_now_add=True)),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cevest.Turma')),
                ('turma_prevista', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cevest.Turma_Prevista')),
            ],
            options={
                'verbose_name_plural': 'Relação entre turma Prevista e Turma Definitiva',
                'ordering': ('turma_prevista', 'turma'),
            },
        ),
    ]
