# Generated by Django 2.1.2 on 2019-01-28 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cevest', '0018_status_aluno_turma_prevista'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno_turma_prevista',
            name='status_aluno_turma_prevista',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='cevest.Status_Aluno_Turma_Prevista'),
        ),
    ]
