# Generated by Django 2.1.2 on 2019-04-30 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cevest', '0020_auto_20190425_0303'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feriado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('data', models.DateField()),
                ('fixo', models.NullBooleanField(default=True, verbose_name='Feriado fixo')),
            ],
            options={
                'verbose_name': 'Feriado',
                'verbose_name_plural': 'Feriados',
            },
        ),
        migrations.CreateModel(
            name='Presenca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_aula', models.DateField(blank=True, null=True, verbose_name='Data da Aula')),
                ('presente', models.BooleanField(blank=True, default=False)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cevest.Aluno')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cevest.Turma')),
            ],
        ),
    ]
