# Generated by Django 2.1.7 on 2019-05-10 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cevest', '0022_auto_20190510_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='nis',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True),
        ),
    ]
