# Generated by Django 4.1.7 on 2023-02-28 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_categoria_cor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curso',
            options={'ordering': ['nome'], 'verbose_name': 'Curso', 'verbose_name_plural': 'Cursos'},
        ),
        migrations.AddField(
            model_name='curso',
            name='banner',
            field=models.ImageField(null=True, upload_to='cursos_livres/media/banner/'),
        ),
    ]
