# Generated by Django 4.1.7 on 2023-02-28 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0003_alter_curso_options_curso_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='icone',
            field=models.ImageField(null=True, upload_to='cursos_livres/media/icone_categoria/'),
        ),
    ]
