# Generated by Django 4.1.7 on 2023-02-28 16:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cursos', '0004_categoria_icone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Palestra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.ImageField(null=True, upload_to='cursos_livres/media/banner/')),
                ('nome', models.CharField(max_length=150)),
                ('sigla', models.CharField(max_length=3, unique=True)),
                ('carga_horaria', models.IntegerField(verbose_name='Carga horária')),
                ('descricao', models.TextField(default='')),
                ('ativo', models.BooleanField(default=True)),
                ('nivel_ensino', models.CharField(choices=[('F', 'Ensino Fundamental'), ('M', 'Ensino Médio'), ('T', 'Ensino Técnico'), ('S', 'Ensino Superior')], max_length=1)),
                ('dt_inclusao', models.DateTimeField(auto_now_add=True)),
                ('dt_alteracao', models.DateField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.categoria')),
                ('instituicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.instituicao')),
                ('requisitos', models.ManyToManyField(to='cursos.requisito')),
                ('user_inclusao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PalestraUserInclusao', to=settings.AUTH_USER_MODEL)),
                ('user_ultima_alteracao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PalestraUserAlteracao', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Palestra',
                'verbose_name_plural': 'Palestras',
                'ordering': ['nome'],
            },
        ),
    ]
