# Generated by Django 4.1.7 on 2023-02-28 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0006_curso_tipo_delete_palestra'),
    ]

    operations = [
        migrations.AddField(
            model_name='instituicao',
            name='local',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cursos.local'),
        ),
    ]
