# Generated by Django 3.2.15 on 2023-04-17 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0008_curso_tipo_carga_horaria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alertar_Aluno_Sobre_Nova_Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_inclusao', models.DateTimeField(auto_now_add=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aluno_interessado', to='cursos.aluno')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curso_de_interesse', to='cursos.aluno')),
            ],
        ),
    ]
