# Generated by Django 3.2.15 on 2023-04-17 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0009_alertar_aluno_sobre_nova_turma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertar_aluno_sobre_nova_turma',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curso_de_interesse', to='cursos.curso'),
        ),
    ]
