# Generated by Django 3.2.15 on 2023-04-17 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0010_alter_alertar_aluno_sobre_nova_turma_curso'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertar_aluno_sobre_nova_turma',
            name='alertado',
            field=models.BooleanField(default=False),
        ),
    ]
