# Generated by Django 3.2.15 on 2023-05-23 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0011_alertar_aluno_sobre_nova_turma_alertado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instituicao_Ensino_Superior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('url', models.URLField()),
            ],
            options={
                'verbose_name': 'Instituição de Ensino Superior',
                'verbose_name_plural': 'Instituições de Ensino Superior',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Curso_Ensino_Superior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('img', models.ImageField(null=True, upload_to='cursos_livres/media/banner_cursos_ensino_superior/')),
                ('instituicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.instituicao_ensino_superior')),
            ],
            options={
                'verbose_name': 'Curso de Ensino Superior',
                'verbose_name_plural': 'Cursos de Ensino Superior',
                'ordering': ['nome'],
            },
        ),
    ]
