# Generated by Django 3.2.15 on 2023-07-12 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0012_curso_ensino_superior_instituicao_ensino_superior'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrutor',
            name='matricula',
            field=models.CharField(blank=True, max_length=150, verbose_name='Mátricula PMNF'),
        ),
    ]
