# Generated by Django 4.2.2 on 2023-08-29 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0014_disciplinas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matricula',
            name='status',
            field=models.CharField(choices=[('c', 'Candidato'), ('s', 'Selecionado'), ('a', 'Aluno'), ('e', 'Desistente'), ('d', 'Desmatriculado'), ('f', 'Formado'), ('r', 'Realocar')], default='c', max_length=1),
        ),
    ]
