# Generated by Django 3.2.15 on 2023-11-09 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0016_disponibilidade_aluno_disponibilidade_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aluno',
            options={'ordering': ['pessoa__nome', 'dt_inclusao'], 'verbose_name': 'Aluno', 'verbose_name_plural': 'Alunos'},
        ),
        migrations.AlterModelOptions(
            name='disponibilidade',
            options={'ordering': ['id'], 'verbose_name': 'Disponibilidade de turno', 'verbose_name_plural': 'Disponibilidade de turnos'},
        ),
        migrations.AlterField(
            model_name='aluno',
            name='aceita_mais_informacoes',
            field=models.BooleanField(default=False, null=True, verbose_name='Declaro que aceito receber email com as informações das atividades'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='li_e_aceito_termos',
            field=models.BooleanField(default=False, null=True, verbose_name='Li e aceito os termos'),
        ),
    ]
