# Generated by Django 4.1.6 on 2023-02-09 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('autenticacao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=64, null=True, verbose_name='Nome/apelido')),
                ('sexo', models.CharField(choices=[('m', 'Macho'), ('f', 'Fêmea')], max_length=1, verbose_name='Sexo do animal')),
                ('castrado', models.BooleanField(default=False, verbose_name='Castrado')),
                ('anilha', models.CharField(blank=True, max_length=64, null=True, verbose_name='Código da anilha')),
                ('animal_image', models.ImageField(blank=True, null=True, upload_to='animal_tutor/', verbose_name='Foto do animal (opcional)')),
                ('dt_inclusao', models.DateField(auto_now_add=True, verbose_name='Data de inclusão')),
            ],
        ),
        migrations.CreateModel(
            name='Catalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=64, null=True, verbose_name='Nome')),
                ('pelagem', models.CharField(max_length=64, verbose_name='Pelagem')),
                ('idade', models.IntegerField(blank=True, null=True, verbose_name='Idade')),
                ('raca', models.CharField(blank=True, max_length=64, null=True, verbose_name='Raça')),
                ('sexo', models.CharField(choices=[('o', 'Macho'), ('a', 'Fêmea')], max_length=1, verbose_name='Sexo do animal')),
                ('castrado', models.BooleanField(default=False, verbose_name='Castrado')),
                ('vacinado', models.BooleanField(default=False, verbose_name='Vacinado')),
                ('animal_image', models.ImageField(blank=True, null=True, upload_to='animal_catalogo/', verbose_name='Foto do animal (opcional)')),
            ],
        ),
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_especie', models.CharField(blank=True, max_length=64, null=True, verbose_name='Espécie')),
            ],
            options={
                'ordering': ['nome_especie'],
            },
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intervalo', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=64, verbose_name='')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_de_moradia', models.CharField(choices=[('Própria', 'Própria'), ('Alugada', 'Alugada')], max_length=7, verbose_name='Tipo de moradia')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autenticacao.pessoa')),
            ],
        ),
        migrations.CreateModel(
            name='TokenDesconto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=12, unique=True)),
                ('used', models.BooleanField(default=False)),
                ('dt_inclusao', models.DateField(auto_now_add=True)),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bemestaranimal.tutor')),
            ],
        ),
        migrations.CreateModel(
            name='Informacoes_Extras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alimentacao_tipo', models.CharField(blank=True, max_length=128, null=True, verbose_name='Tipo de alimentação')),
                ('condicoes', models.CharField(max_length=128, verbose_name='Condições de abrigo na residência')),
                ('dt_vacinacao', models.DateField(blank=True, null=True, verbose_name='Data da última vacinação')),
                ('dt_vermifugacao', models.DateField(blank=True, null=True, verbose_name='Data da última vermifugação')),
                ('complemento', models.CharField(blank=True, max_length=256, null=True, verbose_name='Complemento')),
                ('dt_registro', models.DateField(blank=True, null=True, verbose_name='Data do registro')),
                ('alimentacao_periodo', models.ManyToManyField(to='bemestaranimal.periodo', verbose_name='Período da alimentação')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bemestaranimal.animal')),
            ],
            options={
                'ordering': ['animal'],
            },
        ),
        migrations.CreateModel(
            name='Errante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pelagem', models.CharField(max_length=64, verbose_name='Pelagem')),
                ('animal_image', models.ImageField(blank=True, null=True, upload_to='animal_errante/', verbose_name='Foto do animal (opcional)')),
                ('dt_inclusao', models.DateField(auto_now_add=True, verbose_name='Data de inclusão')),
                ('especie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='bemestaranimal.especie')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bemestaranimal.tipo')),
            ],
        ),
        migrations.CreateModel(
            name='EntrevistaPrevia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=64, verbose_name='Nome')),
                ('cpf', models.CharField(max_length=14, verbose_name='CPF')),
                ('telefone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefone')),
                ('bairro', models.CharField(max_length=64, verbose_name='Bairro')),
                ('endereco', models.CharField(max_length=128, verbose_name='Endereco')),
                ('quest_um', models.CharField(max_length=128, verbose_name='Porque você quer adotar um animal?')),
                ('quest_dois', models.BooleanField(choices=[(True, 'SIM'), (False, 'NÃO')], default=False, verbose_name='Todas as pessoas que residem na casa gostam de animais?')),
                ('quest_tres', models.BooleanField(choices=[(True, 'SIM'), (False, 'NÃO')], default=False, verbose_name='A residência que pretende acolher o animal tem o quintal completamente fechado?')),
                ('quest_quatro', models.BooleanField(choices=[(True, 'SIM'), (False, 'NÃO')], default=False, verbose_name='Você tem consciência de que filhotes exigem cuidados especiais, pois podem chorar, destruir objetos da casa e precisagem de um tempo de adaptação?')),
                ('quest_cinco', models.BooleanField(choices=[(True, 'SIM'), (False, 'NÃO')], default=False, verbose_name='Você tem condições de tratar o animal com ração de qualidade e água limpa diariamente?')),
                ('quest_seis', models.BooleanField(choices=[(True, 'SIM'), (False, 'NÃO')], default=False, verbose_name='Você compromete-se com os cuidados veterinários necessários, além da vacinação anual do animal?')),
                ('quest_sete', models.BooleanField(choices=[(True, 'SIM'), (False, 'NÃO')], default=False, verbose_name='Você tem consciência de que um animal vive cerca de 15 anos e que voc~e teá responsabilidade sobre sua vida durante todo esse tempo?')),
                ('quest_oito', models.BooleanField(choices=[(True, 'SIM'), (False, 'NÃO')], default=False, verbose_name='Você tem plena consciência de que precisará higienizar, diariamente, o espaço onde o animal viverá, estando sujeito ao contato com suas necessidades fisiológicas?')),
                ('quest_nove', models.BooleanField(choices=[(True, 'SIM'), (False, 'NÃO')], default=False, verbose_name='Você tem consciência de que, às vezes o animal poderá fazer suas necessidades em local indesejado?')),
                ('quest_dez', models.BooleanField(choices=[(True, 'SIM'), (False, 'NÃO')], default=False, verbose_name='Você tem consciência de que, como fiel depositário do animal, ele não pode ser doado, vendido ou abandonado sob NENHUMA hipótese?')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bemestaranimal.catalogo')),
            ],
        ),
        migrations.AddField(
            model_name='animal',
            name='especie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='bemestaranimal.especie'),
        ),
        migrations.AddField(
            model_name='animal',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bemestaranimal.tipo'),
        ),
        migrations.AddField(
            model_name='animal',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bemestaranimal.tutor'),
        ),
    ]
