# Generated by Django 4.1.6 on 2023-02-10 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bemestaranimal', '0002_remove_catalogo_animal_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='sexo',
            field=models.CharField(choices=[('o', 'Macho'), ('a', 'Fêmea')], max_length=1, verbose_name='Sexo do animal'),
        ),
        migrations.AlterField(
            model_name='catalogo',
            name='animal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bemestaranimal.animal'),
        ),
    ]
