# Generated by Django 2.0.7 on 2018-09-29 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cevest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='cursos',
            field=models.ManyToManyField(to='cevest.Curso'),
        ),
    ]
