# Generated by Django 2.0.9 on 2018-12-22 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cevest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='quant_alunos',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='curso',
            name='pre_requisito',
            field=models.ManyToManyField(blank=True, to='cevest.Pre_requisito'),
        ),
    ]
