# Generated by Django 2.0.7 on 2018-09-10 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cevest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instrutor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
                ('dt_inclusao', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
