# Generated by Django 2.0.7 on 2018-11-01 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cevest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
                ('carga_horaria', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Matriz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_aulas', models.PositiveSmallIntegerField()),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cevest.Curso')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cevest.Disciplina')),
            ],
            options={
                'verbose_name_plural': 'Matrizes',
            },
        ),
    ]
