# Generated by Django 2.0.9 on 2018-12-26 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cevest', '0002_auto_20181222_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='dt_fim',
            field=models.DateField(blank=True, null=True, verbose_name='Data Fim'),
        ),
        migrations.AddField(
            model_name='turma_prevista',
            name='dt_fim',
            field=models.DateField(blank=True, null=True, verbose_name='Data Fim'),
        ),
    ]
