# Generated by Django 2.0.7 on 2018-09-11 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cevest', '0002_instrutor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
                ('dt_nascimento', models.DateTimeField(verbose_name='date published')),
                ('endereco', models.CharField(max_length=120)),
                ('dt_inclusao', models.DateTimeField(verbose_name='date published')),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bairro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('dt_inclusao', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('dt_inclusao', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
                ('dt_inclusao', models.DateTimeField(verbose_name='date published')),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Escolaridade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50)),
                ('dt_inclusao', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Profissao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('dt_inclusao', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('dt_inclusao', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.DeleteModel(
            name='Cursos',
        ),
        migrations.AddField(
            model_name='instrutor',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='bairro',
            name='cidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cevest.Cidade'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='bairro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cevest.Bairro'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='escolaridade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cevest.Escolaridade'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='profissao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cevest.Profissao'),
        ),
    ]
