# Generated by Django 2.0.9 on 2018-11-25 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cevest', '0002_disciplina_matriz'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aluno',
            options={'ordering': ('nome',)},
        ),
        migrations.AlterModelOptions(
            name='bairro',
            options={'ordering': ('cidade', 'nome')},
        ),
        migrations.AlterModelOptions(
            name='cidade',
            options={'ordering': ('nome',)},
        ),
        migrations.AlterModelOptions(
            name='curso',
            options={'ordering': ('nome',)},
        ),
        migrations.AlterModelOptions(
            name='disciplina',
            options={'ordering': ('nome',)},
        ),
        migrations.AlterModelOptions(
            name='escolaridade',
            options={'ordering': ('descricao',)},
        ),
        migrations.AlterModelOptions(
            name='instrutor',
            options={'ordering': ('nome',), 'verbose_name_plural': 'Instrutores'},
        ),
        migrations.AlterModelOptions(
            name='profissao',
            options={'ordering': ('nome',), 'verbose_name_plural': 'Profissões'},
        ),
        migrations.AddField(
            model_name='aluno',
            name='bolsa_familia',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aluno',
            name='desempregado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aluno',
            name='portador_necessidades_especiais',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aluno',
            name='quant_filhos',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='curso',
            name='conhecimento_avancado_do_sistema_metrico',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='curso',
            name='dominio_da_costura_em_maquinas_industriais',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='curso',
            name='habilidades_manuais',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='curso',
            name='ter_feito_curso_de_costura_plana',
            field=models.BooleanField(default=False),
        ),
    ]
