# Generated by Django 2.0.7 on 2018-09-11 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cevest', '0003_auto_20180911_0448'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instrutor',
            options={'verbose_name_plural': 'Instrutores'},
        ),
        migrations.AlterModelOptions(
            name='profissao',
            options={'verbose_name_plural': 'Profissões'},
        ),
        migrations.AddField(
            model_name='aluno',
            name='cpf',
            field=models.CharField(default='', max_length=11, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aluno',
            name='dt_inclusao',
            field=models.DateTimeField(verbose_name='Data Inclusão'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='dt_nascimento',
            field=models.DateTimeField(verbose_name='Data Inclusão'),
        ),
        migrations.AlterField(
            model_name='bairro',
            name='dt_inclusao',
            field=models.DateTimeField(verbose_name='Data Inclusão'),
        ),
        migrations.AlterField(
            model_name='cidade',
            name='dt_inclusao',
            field=models.DateTimeField(verbose_name='Data Inclusão'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='dt_inclusao',
            field=models.DateTimeField(verbose_name='Data Inclusão'),
        ),
        migrations.AlterField(
            model_name='escolaridade',
            name='dt_inclusao',
            field=models.DateTimeField(verbose_name='Data Inclusão'),
        ),
        migrations.AlterField(
            model_name='instrutor',
            name='dt_inclusao',
            field=models.DateTimeField(verbose_name='Data Inclusão'),
        ),
        migrations.AlterField(
            model_name='profissao',
            name='dt_inclusao',
            field=models.DateTimeField(verbose_name='Data Inclusão'),
        ),
        migrations.AlterField(
            model_name='turno',
            name='dt_inclusao',
            field=models.DateTimeField(verbose_name='Data Inclusão'),
        ),
    ]
