# Generated by Django 2.0.9 on 2018-11-27 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cevest', '0003_auto_20181125_1813'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pre_requisito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
                ('atende', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('descricao',),
            },
        ),
        migrations.RemoveField(
            model_name='curso',
            name='conhecimento_avancado_do_sistema_metrico',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='dominio_da_costura_em_maquinas_industriais',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='habilidades_manuais',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='ter_feito_curso_de_costura_plana',
        ),
        migrations.AddField(
            model_name='curso',
            name='pre_requisito',
            field=models.ManyToManyField(to='cevest.Pre_requisito'),
        ),
    ]
