# Generated by Django 2.0.9 on 2018-12-27 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cevest', '0003_auto_20181226_2145'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='turma_prevista',
            options={'ordering': ('curso',), 'verbose_name': 'Turma Prevista', 'verbose_name_plural': 'Turmas Previstas'},
        ),
    ]
