# Generated by Django 2.0.7 on 2018-09-12 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cevest', '0004_auto_20180911_0537'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno_Quer_Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_inclusao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='aluno',
            name='dt_inclusao',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='escolaridade',
            name='dt_inclusao',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name='aluno_quer_curso',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cevest.Aluno'),
        ),
        migrations.AddField(
            model_name='aluno_quer_curso',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cevest.Curso'),
        ),
    ]
