# Generated by Django 2.0.9 on 2018-11-27 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cevest', '0004_auto_20181127_1528'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pre_requisito',
            options={'ordering': ('descricao',), 'verbose_name': 'Pré-Requisito'},
        ),
        migrations.RemoveField(
            model_name='pre_requisito',
            name='atende',
        ),
    ]
