# Generated by Django 2.0.9 on 2018-12-11 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cevest', '0005_auto_20181127_1540'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno_Turma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_inclusao', models.DateTimeField(auto_now_add=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cevest.Aluno')),
            ],
            options={
                'ordering': ('turma', 'aluno'),
            },
        ),
        migrations.CreateModel(
            name='Curriculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('dt_inicio', models.DateField(verbose_name='Data Início')),
                ('dt_fim', models.DateField(blank=True, null=True, verbose_name='Data Fim')),
                ('dt_inclusao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('dt_fim', 'nome'),
            },
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.CharField(choices=[('1', 'Domingo'), ('2', 'Segunda'), ('3', 'Terça'), ('4', 'Quarta'), ('5', 'Quinta'), ('6', 'Sexta'), ('7', 'Sábado')], max_length=1)),
                ('hora_inicio', models.TimeField(verbose_name='Hora Início')),
                ('hora_fim', models.TimeField(verbose_name='Hora Fim')),
                ('dt_inclusao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('turma_prevista',),
            },
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_inicio', models.DateField(verbose_name='Data Início')),
                ('dt_inclusao', models.DateTimeField(auto_now_add=True)),
                ('curriculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cevest.Curriculo')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cevest.Curso')),
            ],
            options={
                'ordering': ('curso',),
            },
        ),
        migrations.CreateModel(
            name='Turma_Prevista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_inicio', models.DateField(verbose_name='Data Início')),
                ('dt_inclusao', models.DateTimeField(auto_now_add=True)),
                ('curriculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cevest.Curriculo')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cevest.Curso')),
            ],
            options={
                'ordering': ('curso',),
            },
        ),
        migrations.AddField(
            model_name='horario',
            name='turma_prevista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cevest.Turma_Prevista'),
        ),
        migrations.AddField(
            model_name='aluno_turma',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cevest.Turma'),
        ),
        migrations.AddField(
            model_name='matriz',
            name='curriculo',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.PROTECT, to='cevest.Curriculo'),
        ),
    ]
