# Generated by Django 2.0.9 on 2019-01-07 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cevest', '0009_auto_20181227_0040'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='horario',
            options={'ordering': ('dia_semana', 'hora_inicio', 'hora_fim')},
        ),
        migrations.AlterModelOptions(
            name='turma_prevista',
            options={'ordering': ('curso', 'nome'), 'verbose_name': 'Turma Prevista', 'verbose_name_plural': 'Turmas Previstas'},
        ),
        migrations.AddField(
            model_name='aluno',
            name='ordem_judicial',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aluno',
            name='outro_profissao',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='exibir',
            field=models.BooleanField(default=True),
        ),
    ]
