# Generated by Django 2.0.9 on 2019-01-07 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cevest', '0010_auto_20190107_0034'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aluno_turma',
            options={'ordering': ('turma', 'aluno'), 'verbose_name_plural': 'Relação de Alunos por Turma'},
        ),
        migrations.RenameField(
            model_name='aluno',
            old_name='outro_profissao',
            new_name='outra_profissao',
        ),
        migrations.AddField(
            model_name='aluno',
            name='cep',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='aluno',
            name='complemento',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
