# Generated by Django 2.1.2 on 2019-01-09 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cevest', '0012_auto_20190107_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma_prevista',
            name='exibir',
            field=models.BooleanField(default=True),
        ),
    ]
