# Generated by Django 2.1.2 on 2019-01-18 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cevest', '0013_turma_prevista_exibir'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno_Turma_Prevista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_inclusao', models.DateTimeField(auto_now_add=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cevest.Aluno')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cevest.Turma')),
            ],
            options={
                'ordering': ('turma', 'aluno'),
                'verbose_name_plural': 'Relação de Alunos por Turma - Previsão',
            },
        ),
    ]
