# Generated by Django 2.1.2 on 2019-01-21 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cevest', '0014_aluno_turma_prevista'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno_turma_prevista',
            name='aluno',
        ),
        migrations.RemoveField(
            model_name='aluno_turma_prevista',
            name='turma',
        ),
        migrations.DeleteModel(
            name='Aluno_Turma_Prevista',
        ),
    ]
