# Generated by Django 2.1.2 on 2019-01-28 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cevest', '0017_turma_prevista_turma_definitiva'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status_Aluno_Turma_Prevista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=60, unique=True)),
                ('dt_inclusao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('descricao',),
                'verbose_name_plural': 'Status de Alunos por Turma Prevista',
            },
        ),
    ]
