# Generated by Django 2.1.7 on 2019-04-10 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cevest', '0019_aluno_turma_prevista_status_aluno_turma_prevista'),
    ]

    operations = [
        migrations.CreateModel(
            name='Situacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=10, null=True, unique=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='turma',
            options={'ordering': ('curso', 'nome')},
        ),
        migrations.AddField(
            model_name='instrutor',
            name='matricula',
            field=models.CharField(max_length=11, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='cpf',
            field=models.CharField(max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='nis',
            field=models.CharField(max_length=11, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='aluno_turma',
            name='situacao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cevest.Situacao'),
        ),
    ]
