# Generated by Django 2.1.9 on 2019-06-14 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cevest', '0019_aluno_turma_prevista_status_aluno_turma_prevista'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feriado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('data', models.DateField()),
                ('fixo', models.NullBooleanField(default=True, verbose_name='Feriado fixo')),
            ],
            options={
                'verbose_name': 'Feriado',
                'verbose_name_plural': 'Feriados',
            },
        ),
        migrations.CreateModel(
            name='Presenca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_aula', models.DateField(blank=True, null=True, verbose_name='Data da Aula')),
                ('presente', models.BooleanField(blank=True, default=False)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cevest.Aluno')),
            ],
        ),
        migrations.CreateModel(
            name='Situacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=10, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Situação',
                'verbose_name_plural': 'Situações',
            },
        ),
        migrations.CreateModel(
            name='Situacao_Turma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=10, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Situação de turma',
                'verbose_name_plural': 'Situações de turma',
            },
        ),
        migrations.AlterModelOptions(
            name='turma',
            options={'ordering': ('curso', 'nome')},
        ),
        migrations.AddField(
            model_name='instrutor',
            name='matricula',
            field=models.CharField(max_length=11, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='matriz',
            name='carga_horaria_total',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='curso',
            name='duracao',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='curso',
            name='escolaridade_minima',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='cevest.Escolaridade'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='idade_minima',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='carga_horaria',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='presenca',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cevest.Turma'),
        ),
        migrations.AddField(
            model_name='aluno_turma',
            name='situacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cevest.Situacao'),
        ),
        migrations.AddField(
            model_name='turma_prevista',
            name='situacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cevest.Situacao_Turma'),
        ),
    ]
