# Generated by Django 2.1.2 on 2019-04-25 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cevest', '0019_aluno_turma_prevista_status_aluno_turma_prevista'),
    ]

    operations = [
        migrations.CreateModel(
            name='Situacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=10, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Situação',
                'verbose_name_plural': 'Situações',
            },
        ),
        migrations.AlterModelOptions(
            name='turma',
            options={'ordering': ('curso', 'nome')},
        ),
        migrations.AddField(
            model_name='instrutor',
            name='matricula',
            field=models.CharField(max_length=11, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='matriz',
            name='carga_horaria_total',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aluno',
            name='nis',
            field=models.CharField(max_length=11, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='curso',
            name='duracao',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='curso',
            name='escolaridade_minima',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='cevest.Escolaridade'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='idade_minima',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='carga_horaria',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='aluno_turma',
            name='situacao',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='cevest.Situacao'),
        ),
    ]
