# Generated by Django 2.1.7 on 2019-04-10 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cevest', '0020_auto_20190410_1121'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='situacao',
            options={'verbose_name': 'Situação', 'verbose_name_plural': 'Situações'},
        ),
    ]
