# Generated by Django 2.1.9 on 2019-07-08 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cevest', '0021_auto_20190628_0143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='situacao',
            name='descricao',
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
    ]
