# Generated by Django 2.1.7 on 2019-04-10 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cevest', '0021_auto_20190410_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno_turma',
            name='situacao',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='cevest.Situacao'),
            preserve_default=False,
        ),
    ]
