# Generated by Django 2.1.7 on 2019-05-10 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cevest', '0021_feriado_presenca'),
    ]

    operations = [
        migrations.CreateModel(
            name='Situacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=10, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Situação',
                'verbose_name_plural': 'Situações',
            },
        ),
        migrations.AddField(
            model_name='instrutor',
            name='matricula',
            field=models.CharField(max_length=11, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='matriz',
            name='carga_horaria_total',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aluno_turma',
            name='situacao',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='cevest.Situacao'),
        ),
    ]
