# Generated by Django 2.1.11 on 2019-09-23 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cevest', '0022_auto_20190707_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno_turma',
            name='situacao',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='cevest.Situacao'),
        ),
    ]
