# Generated by Django 2.1.2 on 2019-12-09 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cevest', '0023_auto_20190923_1057'),
    ]

    operations = [
        
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('ativo', models.BooleanField(default=True)),
                ('dt_inclusao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
    ]
