# Generated by Django 2.1.7 on 2019-04-10 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cevest', '0023_remove_aluno_turma_situacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno_turma',
            name='situacao',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='cevest.Situacao'),
            preserve_default=False,
        ),
    ]
