# Generated by Django 2.1.7 on 2019-05-10 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cevest', '0023_auto_20190510_1406'),
    ]

    operations = [
        migrations.CreateModel(
            name='Situacao_Turma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=10, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Situação de turma',
                'verbose_name_plural': 'Situações de turma',
            },
        ),
    ]
