# Generated by Django 2.1.2 on 2019-12-09 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cevest', '0024_programa'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='programa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='cevest.Programa'),
        ),
    ]
