# Generated by Django 2.1.7 on 2019-05-10 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cevest', '0024_situacao_turma'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma_prevista',
            name='situacao',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='cevest.Situacao_Turma'),
        ),
    ]
