# Generated by Django 2.1.7 on 2019-04-11 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cevest', '0024_aluno_turma_situacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permissao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('pode_emitir_certificado', 'Pode emitir certificados'),),
            },
        ),
    ]
