# Generated by Django 2.2.5 on 2019-12-16 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cevest', '0025_curso_programa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Situacao_Turma_Definitiva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'verbose_name': 'Situação de turma definitiva',
                'verbose_name_plural': 'Situações de turma definitiva',
            },
        ),
        migrations.AlterModelOptions(
            name='situacao_turma',
            options={'verbose_name': 'Situação de turma prevista', 'verbose_name_plural': 'Situações de turma prevista'},
        ),
        migrations.AddField(
            model_name='turma',
            name='dt_fechamento',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data Fechamento'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='nome',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='turma',
            name='dt_fim',
            field=models.DateField(verbose_name='Data Fim'),
        ),
        migrations.AlterField(
            model_name='turma_prevista',
            name='situacao',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='cevest.Situacao_Turma'),
        ),
    ]
