# Generated by Django 2.1.7 on 2019-04-11 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cevest', '0025_permissao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permissao',
            options={'permissions': (('pode_emitir_certificado', 'Pode emitir certificados'), ('acesso_admin', 'Acesso à area de admin'))},
        ),
    ]
