# Generated by Django 2.2.9 on 2020-01-22 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cevest', '0026_auto_20191216_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bairro',
            name='nome',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='cidade',
            name='nome',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='escolaridade',
            name='descricao',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='pre_requisito',
            name='descricao',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='programa',
            name='nome',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
