# Generated by Django 2.1.7 on 2019-04-11 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cevest', '0026_auto_20190411_1028'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Permissao',
        ),
        migrations.AddField(
            model_name='matriz',
            name='carga_horaria_total',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
