# Generated by Django 2.1.7 on 2019-04-18 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cevest', '0028_auto_20190417_1350'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presenca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_aula', models.DateTimeField(blank=True, null=True, verbose_name='Data da Aula')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cevest.Aluno')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cevest.Turma')),
            ],
        ),
    ]
