# Generated by Django 4.0.1 on 2022-03-15 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cevest', '0028_turma_exibir_turma_situacao_alter_aluno_id_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='aluno_turma_prevista',
            unique_together={('turma_prevista', 'aluno')},
        ),
    ]
