# Generated by Django 2.1.7 on 2019-04-25 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cevest', '0029_presenca'),
    ]

    operations = [
        migrations.AddField(
            model_name='presenca',
            name='presente',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='presenca',
            name='data_aula',
            field=models.DateField(blank=True, null=True, verbose_name='Data da Aula'),
        ),
    ]
