# Generated by Django 3.2.16 on 2023-01-01 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cevest', '0029_alter_aluno_turma_prevista_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='comprovante_residencia_file',
            field=models.FileField(blank=True, null=True, upload_to='comprovante_residencia_file', verbose_name='Comproante de residência'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='cpf_file',
            field=models.FileField(blank=True, null=True, upload_to='cpf_file', verbose_name='CPF'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='identidade_file',
            field=models.FileField(blank=True, null=True, upload_to='identidade_file', verbose_name='Identidade'),
        ),
    ]
