# Generated by Django 2.1.7 on 2019-04-26 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cevest', '0030_auto_20190425_1340'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feriado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('data', models.DateField()),
            ],
            options={
                'verbose_name': 'Feriado',
                'verbose_name_plural': 'Feriados',
            },
        ),
    ]
