# Generated by Django 2.1.7 on 2019-04-26 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cevest', '0031_feriado'),
    ]

    operations = [
        migrations.AddField(
            model_name='feriado',
            name='fixo',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Feriado fixo'),
        ),
    ]
