# Generated by Django 3.2.16 on 2023-01-02 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cevest', '0031_auto_20230101_1857'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pre_requisito',
            options={'ordering': ('descricao',), 'verbose_name': 'Pré-requisito', 'verbose_name_plural': 'Pré-requisitos'},
        ),
        migrations.RemoveField(
            model_name='escolaridade',
            name='dt_inclusao',
        ),
    ]
