# Generated by Django 2.1.7 on 2019-04-26 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cevest', '0032_feriado_fixo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feriado',
            name='data',
            field=models.DateField(unique=True),
        ),
        migrations.AlterField(
            model_name='feriado',
            name='nome',
            field=models.CharField(max_length=50),
        ),
    ]
