# Generated by Django 2.1.7 on 2019-04-26 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cevest', '0033_auto_20190426_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feriado',
            name='data',
            field=models.DateField(),
        ),
    ]
