# Generated by Django 4.2.2 on 2023-08-29 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0002_alter_pessoa_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='numero',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Número'),
        ),
    ]
