# Generated by Django 4.2.2 on 2023-10-31 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0004_alter_pessoa_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='nome',
            field=models.CharField(max_length=64, verbose_name='Nome completo'),
        ),
    ]
