# Generated by Django 3.2.15 on 2023-11-09 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0005_alter_pessoa_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='possui_cnpj',
            field=models.BooleanField(default=False, verbose_name='Você possui empresa?'),
        ),
    ]
