# Generated by Django 3.2.17 on 2023-03-07 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel_Index',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=64, verbose_name='Nome para identificação ou para texto alternativo')),
                ('image', models.ImageField(null=True, upload_to='carousel_index/', verbose_name='Imagem 987x394')),
                ('ativa', models.BooleanField(default=True)),
            ],
        ),
    ]
