# Generated by Django 3.2.15 on 2023-04-17 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desenvolve_nf', '0003_climatempo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='climatempo',
            name='madrugada',
            field=models.CharField(blank=True, max_length=50, verbose_name='Clima na madrugada'),
        ),
        migrations.AlterField(
            model_name='climatempo',
            name='manha',
            field=models.CharField(blank=True, max_length=50, verbose_name='Clima na manhã'),
        ),
        migrations.AlterField(
            model_name='climatempo',
            name='noite',
            field=models.CharField(blank=True, max_length=50, verbose_name='Clima na noite'),
        ),
        migrations.AlterField(
            model_name='climatempo',
            name='tarde',
            field=models.CharField(blank=True, max_length=50, verbose_name='Clima na tarde'),
        ),
    ]
